/**
* MIT License
*
* Copyright (c) 2021-2022 Manuel Bottini
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:

* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.

* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

#include <Arduino.h>
#include "constants.h"

// Implements Specification Version Dev 1.0
// Sensortypes: orientation_abs, acceleration_rel, glove
// Board: RedBear Duo (Native USB Port)

#ifndef __WIFI_NODE_BASICS_H
#define __WIFI_NODE_BASICS_H

#define BODYNODE_BODYPART_HEX BODYPART_LOWERLEG_RIGHT_HEX
#define BODYNODE_PLAYER_DEFAULT_TAG  "mario"

// #define BODYNODE_GLOVE_SENSOR

// If BODYNODE_GLOVE_SENSOR is defined then BODYNODE_BODYPART_GLOVE_TAG will be defined in case the node is a forearm
// Note that only forearm nodes can have gloves, therefore BODYNODE_GLOVE_SENSOR is undefined for the other cases
#if BODYNODE_BODYPART_HEX == BODYPART_LOWERARM_RIGHT_HEX
  #define BODYNODE_BODYPART_GLOVE_TAG BODYPART_HAND_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERARM_LEFT_HEX
  #define BODYNODE_BODYPART_GLOVE_TAG BODYPART_HAND_LEFT_TAG
#else
  #undef BODYNODE_GLOVE_SENSOR
#endif // BODYNODE_BODYPART_HEX != BODYPART_LOWERARM_RIGHT_HEX && BODYNODE_BODYPART_HEX != BODYPART_LOWERARM_LEFT_HEX

#define BODYNODE_SHOE_SENSOR

// If BODYNODE_SHOE_SENSOR is defined then BODYNODE_BODYPART_SHOE_TAG will be defined in case the node is a lowerleg
// Note that only forearm nodes can have gloves, therefore BODYNODE_GLOVE_SENSOR is undefined for the other cases
#if BODYNODE_BODYPART_HEX == BODYPART_LOWERLEG_RIGHT_HEX
  #define BODYNODE_BODYPART_SHOE_TAG BODYPART_FOOT_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERLEG_LEFT_HEX
  #define BODYNODE_BODYPART_SHOE_TAG BODYPART_FOOT_LEFT_TAG
#else
  #undef BODYNODE_SHOE_SENSOR
#endif // BODYNODE_BODYPART_HEX != BODYPART_LOWERLEG_RIGHT_HEX && BODYNODE_BODYPART_HEX != BODYPART_LOWERLEG_LEFT_HEX

#define SENSOR_READ_INTERVAL_MS 30
#define BIG_QUAT_DIFF 0.002
#define CONNECTION_ACK_INTERVAL_MS 1000
#define CONNECTION_KEEP_ALIVE_SEND_INTERVAL_MS 30000
#define CONNECTION_KEEP_ALIVE_REC_INTERVAL_MS 60000

// Device Specific Axis Configuration
// Use the program "sensor_test" and check the "bodynodes universal orientation specs" to build your axis configuration,
// so that your node can easily integrate with any system.
#define SENSOR_AXIS_W 0
#define SENSOR_AXIS_X 1
#define SENSOR_AXIS_Y 2
#define SENSOR_AXIS_Z 3

#define OUT_AXIS_W SENSOR_AXIS_Z
#define OUT_AXIS_X SENSOR_AXIS_Y
#define OUT_AXIS_Y SENSOR_AXIS_X
#define OUT_AXIS_Z SENSOR_AXIS_W

#define MUL_AXIS_W -1
#define MUL_AXIS_X 1
#define MUL_AXIS_Y -1
#define MUL_AXIS_Z 1

// PINS
#define BUZZER_FREQ 1000 //Specified in Hz
#define LED_DT_ON 30 // Duty cicle of LED ON

#define STATUS_SENSOR_HMI_LED_P      6
#define STATUS_SENSOR_HMI_LED_M      5
#define STATUS_CONNECTION_HMI_LED_P  3
#define STATUS_CONNECTION_HMI_LED_M  2
#define HAPTIC_MOTOR_PIN_P           10
#define HAPTIC_MOTOR_PIN_M           11
#define SHOE_SENSOR_PIN_P            19

#define MAX_BUFF_LENGTH 100

#define DEBUG_M
#ifdef DEBUG_M
 #define DEBUG_PRINT(x)  Serial.print (x)
 #define DEBUG_PRINT_HEX(x)  Serial.print (x,HEX)
 #define DEBUG_PRINT_DEC(x)  Serial.print (x,DEC)
 #define DEBUG_PRINTLN(x)  Serial.println (x)
 #define DEBUG_PRINTLN_HEX(x)  Serial.println (x,HEX)
 #define DEBUG_PRINTLN_DEC(x)  Serial.println (x,DEC)
#else
 #define DEBUG_PRINT(x)
 #define DEBUG_PRINT_HEX(x)
 #define DEBUG_PRINT_DEC(x)
 #define DEBUG_PRINTLN(x)
 #define DEBUG_PRINTLN_HEX(x)
 #define DEBUG_PRINTLN_DEC(x)
#endif

#define BODYNODES_PORT 12345
#define BODYNODES_MULTICAST_PORT 12346

#define BODYNODES_WIFI_SSID_DEFAULT "BodyodesHotspot"
#define BODYNODES_WIFI_PASS_DEFAULT "bodynodes1"
#define BODYNODES_MULTICASTIP_DEFAULT  "239.192.1.99"

#define BODYNODES_WIFI_SSID_DEFAULT "BTHub6-X87G"
#define BODYNODES_WIFI_PASS_DEFAULT "CGHpVUCfALn4"

// Set BODYNODE_BODYPART_TAG
#if BODYNODE_BODYPART_HEX == BODYPART_HEAD_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_HEAD_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_HAND_LEFT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_HAND_LEFT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERARM_LEFT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_LOWERARM_LEFT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_UPPERARM_LEFT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_UPPERARM_LEFT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_BODY_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_BODY_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERARM_RIGHT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_LOWERARM_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_UPPERARM_RIGHT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_UPPERARM_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_HAND_RIGHT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_HAND_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERLEG_LEFT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_LOWERLEG_LEFT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_UPPERLEG_LEFT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_UPPERLEG_LEFT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_FOOT_LEFT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_FOOT_LEFT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERLEG_RIGHT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_LOWERLEG_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_UPPERLEG_RIGHT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_UPPERLEG_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_FOOT_RIGHT_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_FOOT_RIGHT_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_UPPERBODY_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_UPPERBODY_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_LOWERBODY_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_LOWERBODY_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_KATANA_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_KATANA_TAG
#elif BODYNODE_BODYPART_HEX == BODYPART_UNTAGGED_HEX
  #define BODYNODE_BODYPART_TAG BODYPART_UNTAGGED_TAG
#endif // BODYNODE_BODYPART_TAG 

#endif //__WIFI_NODE_BASICS_H
