/**
* MIT License
*
* Copyright (c) 2019-2025 Manuel Bottini
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:

* The above copyright notice and this permission notice shall be included in all
* copies or substantial portions of the Software.

* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

#ifndef __BN_CONSTANTS_H
#define __BN_CONSTANTS_H

#define BN_PLAYER_ALL_TAG "all"
#define BN_PLAYER_NONE_TAG "none"

// BODY PARTS NAMES
#define BN_BODYPART_NONE_TAG "none"
#define BN_BODYPART_HEAD_TAG "head"
#define BN_BODYPART_HAND_LEFT_TAG "hand_left"
#define BN_BODYPART_LOWERARM_LEFT_TAG "lowerarm_left"
#define BN_BODYPART_UPPERARM_LEFT_TAG "upperarm_left"
#define BN_BODYPART_BODY_TAG "body"
#define BN_BODYPART_LOWERARM_RIGHT_TAG "lowerarm_right"
#define BN_BODYPART_UPPERARM_RIGHT_TAG "upperarm_right"
#define BN_BODYPART_HAND_RIGHT_TAG "hand_right"
#define BN_BODYPART_LOWERLEG_LEFT_TAG "lowerleg_left"
#define BN_BODYPART_UPPERLEG_LEFT_TAG "upperleg_left"
#define BN_BODYPART_FOOT_LEFT_TAG "foot_left"
#define BN_BODYPART_LOWERLEG_RIGHT_TAG "lowerleg_right"
#define BN_BODYPART_UPPERLEG_RIGHT_TAG "upperleg_right"
#define BN_BODYPART_FOOT_RIGHT_TAG "foot_right"
#define BN_BODYPART_UPPERBODY_TAG "upperbody"
#define BN_BODYPART_LOWERBODY_TAG "lowerbody"
#define BN_BODYPART_KATANA_TAG "katana"
#define BN_BODYPART_UNTAGGED_TAG "untagged"
#define BN_BODYPART_ALL_TAG "all"

// BODY PARTS HEX CODES (Important for the preprocessing macros)
#define BN_BODYPART_NONE_HEX 0x0000
#define BN_BODYPART_HEAD_HEX 0x0001
#define BN_BODYPART_HAND_LEFT_HEX 0x0002
#define BN_BODYPART_LOWERARM_LEFT_HEX 0x0003
#define BN_BODYPART_UPPERARM_LEFT_HEX 0x0004
#define BN_BODYPART_BODY_HEX 0x0005
#define BN_BODYPART_LOWERARM_RIGHT_HEX 0x0006
#define BN_BODYPART_UPPERARM_RIGHT_HEX 0x0007
#define BN_BODYPART_HAND_RIGHT_HEX 0x0009
#define BN_BODYPART_LOWERLEG_LEFT_HEX 0x0009
#define BN_BODYPART_UPPERLEG_LEFT_HEX 0x000A
#define BN_BODYPART_FOOT_LEFT_HEX 0x000B
#define BN_BODYPART_LOWERLEG_RIGHT_HEX 0x000C
#define BN_BODYPART_UPPERLEG_RIGHT_HEX 0x000D
#define BN_BODYPART_FOOT_RIGHT_HEX 0x000E
#define BN_BODYPART_UPPERBODY_HEX 0x000F
#define BN_BODYPART_LOWERBODY_HEX 0x0010
#define BN_BODYPART_KATANA_HEX 0x0011
#define BN_BODYPART_UNTAGGED_HEX 0x0012
#define BN_BODYPART_ALL_HEX 0xFFFE // Used in some particular cases

// ACTIONS
#define BN_ACTION_TYPE_TAG "type"
#define BN_ACTION_PLAYER_TAG "player"
#define BN_ACTION_BODYPART_TAG "bodypart"

#define BN_ACTION_TYPE_NONE_TAG "none"
#define BN_ACTION_TYPE_HAPTIC_TAG "haptic"
#define BN_ACTION_TYPE_SETPLAYER_TAG "set_player"
#define BN_ACTION_TYPE_SETBODYPART_TAG "set_bodypart"
#define BN_ACTION_TYPE_ENABLESENSOR_TAG "enable_sensor"
#define BN_ACTION_TYPE_SETWIFI_TAG "set_wifi"

#define BN_ACTION_HAPTIC_DURATION_MS_TAG "duration_ms"
#define BN_ACTION_HAPTIC_STRENGTH_TAG "strength"
#define BN_ACTION_SETPLAYER_NEWPLAYER_TAG "new_player"
#define BN_ACTION_SETBODYPART_NEWBODYPART_TAG "new_bodypart"
#define BN_ACTION_ENABLESENSOR_SENSORTYPE_TAG "sensortype"
#define BN_ACTION_ENABLESENSOR_ENABLE_TAG "enable"
#define BN_ACTION_SETWIFI_SSID_TAG "ssid"
#define BN_ACTION_SETWIFI_PASSWORD_TAG "password"
#define BN_ACTION_SETWIFI_MULTICASTMESSAGE_TAG "multicast_message"

// MESSAGE
#define BN_MESSAGE_PLAYER_TAG "player"
#define BN_MESSAGE_BODYPART_TAG "bodypart"
#define BN_MESSAGE_SENSORTYPE_TAG "sensortype"
#define BN_MESSAGE_VALUE_TAG "value"

// GLOVE
#define BN_GLOVE_ANGLE_MIGNOLO_INDEX 0
#define BN_GLOVE_ANGLE_ANULARE_INDEX 1
#define BN_GLOVE_ANGLE_MEDIO_INDEX 2
#define BN_GLOVE_ANGLE_INDICE_INDEX 3
#define BN_GLOVE_ANGLE_POLLICE_INDEX 4
#define BN_GLOVE_TOUCH_MIGNOLO_INDEX 5
#define BN_GLOVE_TOUCH_ANULARE_INDEX 6
#define BN_GLOVE_TOUCH_MEDIO_INDEX 7
#define BN_GLOVE_TOUCH_INDICE_INDEX 8

// MEMORY
#define BN_MEMORY_BODYPART_TAG "bodypart"
#define BN_MEMORY_BODYPART_GLOVE_TAG "bodypart_glove"
#define BN_MEMORY_BODYPART_SHOE_TAG "bodypart_shoe"
#define BN_MEMORY_PLAYER_TAG "player"
#define BN_MEMORY_WIFI_SSID_TAG "wifi_ssid"
#define BN_MEMORY_WIFI_PASSWORD_TAG "wifi_password"
#define BN_MEMORY_WIFI_MULTICASTMESSAGE_TAG "multicast_message"

// SENSOR DATA TYPES
#define BN_SENSORTYPE_NONE_TAG "none"
#define BN_SENSORTYPE_ORIENTATION_ABS_TAG "orientation_abs"
#define BN_SENSORTYPE_ACCELERATION_REL_TAG "acceleration_rel"
#define BN_SENSORTYPE_GLOVE_TAG "glove"
#define BN_SENSORTYPE_SHOE_TAG "shoe"
#define BN_SENSORTYPE_ANGULARVELOCITY_REL_TAG "angularvelocity_rel"

// SENSOR STATUS
#define BN_SENSOR_STATUS_NOT_ACCESSIBLE 1
#define BN_SENSOR_STATUS_CALIBRATING 2
#define BN_SENSOR_STATUS_WORKING 3

// CONNECTION STATUS
#define BN_CONNECTION_STATUS_NOT_CONNECTED 0
#define BN_CONNECTION_STATUS_WAITING_ACK 1
#define BN_CONNECTION_STATUS_CONNECTED 2

// Wifi Connections
#define BN_WIFI_PORT 12345
#define BN_WIFI_MULTICAST_PORT 12346
#define BN_WIFI_SSID_DEFAULT "BodynodeHotspot"
#define BN_WIFI_PASSWORD_DEFAULT "bodynodes1"
#define BN_WIFI_MULTICASTGROUP_DEFAULT "239.192.1.99"
#define BN_WIFI_MULTICASTMESSAGE_DEFAULT "BN"

// Bluetooth Connections -> TODO

// BLE Connections
#define BN_BLE_NAME "Bodynode"
#define BN_BLE_SERVICE_UUID "0000CCA0-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_PLAYER_UUID "0000CCA1-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_BODYPART_UUID "0000CCA2-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_ORIENTATION_ABS_VALUE_UUID "0000CCA3-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_ACCELERATION_REL_VALUE_UUID "0000CCA4-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_GLOVE_VALUE_UUID "0000CCA5-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_SHOE_UUID "0000CCA6-0000-1000-8000-00805F9B34FB"
#define BN_BLE_CHARA_ANGULARVELOCITY_REL_VALUE_UUID "0000CCA7-0000-1000-8000-00805F9B34FB"

/////////////////// GENERIC

#define BN_M_PI 3.141592653589793

#endif //__BN_CONSTANTS_H